### PR TITLE
[PR] Verbosity Output for Clear Main Execution

### PR DESCRIPTION
**Pull request by rob4abcba**
Add print statements so output from IterationTraversal.java is more readable and understandable.  Currently, the output looks like just a bunch of numbers.  Add print statements so people know which numbers correspond to which array/matrix and whether they are seeing the array/matrix before or after the flip or sort operation.

### CODE REVIEW

**Comment by awkonecki** [comment]
@rob4abcba thanks for the PR.  For your next set of commits, try to keep the PR title to less than 80 characters.  I will add a template for commits later, maybe tomorrow for how to follow for contributions.  For future reference prior to the template being available please follow the following.

```
[FTR] Simple Feature Description

Feature Description

You paragraph.  The number below should be an issue that you are pulling against that exists within the repository.

Related Issues
- #11111
```

**Comment by awkonecki** [comment]
Addresses [Issue #4](#4).

**Comment by awkonecki** [comment]
@rob4abcba Also a suggestion for Pull Requests in the future, if possible keep them as concise as possible.  This one is really two separate features.

First is verbosity printing.
Second is the range exercise.

If there is a bug you don't need to create comments in the code.  Just create and issue and point it out in the code.

For your first one though no problem, takes time to get used, and I did not provide guidance for contribution rules.

**Comment by rob4abcba** [comment]
Yes, I intended for my  addition of an implementation of findRange to be a separate pull request, but I guess since that local change was to the same file, it got lumped in with my initial [PR] Verbosity Output for Clear Main Execution #10 when I did the Compare Forks.

**Comment by awkonecki** [comment]
@rob4abcba yeah.  You would have to have created another branched and pushed it separately to get the desired effect of address the two issues.

**Comment by rob4abcba** [comment]
Oh, I think I understand.  I had seen that you had named your topic branches arrays and linked-lists, so I thought that I should name my branches the same.  Seems like actually I did not have to limit myself to naming my branch arrays.  Instead I should have called my first branch something like "verbosity" and my second branch something like "findRange" so that I could have kept them as separate pull requests even though they were changes to the same file, right?

**Pull request merged**
